# Site settings
title: 海品照明 - 专业商业照明服务商
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sd.ycz.im" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: /blog/:title

# Build settings
markdown: kramdown


# 样式资源主地址
qiniu: /
# UGC资源地址
qiniu_upload: https://zico.oss-cn-beijing.aliyuncs.com/test/

home_startups:
  - 卓越三维 
  - 海导科技
  - 慕声定制耳机
  - 拓奇科技

product_categories:
  - 导轨灯
  - LED 天花射灯
  - LED 伸缩灯
  - 栅格灯
  - 迷你栅格灯
  - 筒灯
  - 明装筒灯
  - 模组化射灯
  - LED 酒柜灯
  - 酒店洗墙灯
  - 吊线灯
  - 壁灯地灯

# 站点信息
slogan: 致力于早期科技创业孵化
qrcode: qrcode.jpg

brand_color: #9fcb4f

collections:
  product:
    output: true